from enum import Enum


class RiskReasonCode(str, Enum):
    OK = "RISK_OK"
    MODE_NOT_ARMED = "RISK_MODE_NOT_ARMED"
    DATA_STALE = "RISK_DATA_STALE"
    UNKNOWN_ORDER = "RISK_UNKNOWN_ORDER"
    DUPLICATE_CLIENT_ORDER_ID = "RISK_DUPLICATE_CLIENT_ORDER_ID"
    ACCOUNT_MISMATCH = "RISK_ACCOUNT_MISMATCH"
    INTENT_EXPIRED = "RISK_INTENT_EXPIRED"
    INVALID_ORDER = "RISK_INVALID_ORDER"
    LIMIT_EXCEEDED = "RISK_LIMIT_EXCEEDED"
    STRATEGY_NOT_ALLOWED = "RISK_STRATEGY_NOT_ALLOWED"
    MARKET_CLOSED = "RISK_MARKET_CLOSED"
    DATABASE_UNHEALTHY = "RISK_DATABASE_UNHEALTHY"
    LEADER_NOT_HELD = "RISK_LEADER_NOT_HELD"


class SystemErrorCode(str, Enum):
    TRADING_DISABLED = "E_TRADING_DISABLED"
    INVALID_TRANSITION = "E_INVALID_TRANSITION"
    DUPLICATE_CLIENT_ORDER_ID = "E_DUPLICATE_CLIENT_ORDER_ID"
    UNKNOWN_ORDER_BLOCK = "E_UNKNOWN_ORDER_BLOCK"
    PROTOCOL_UNSUPPORTED = "E_PROTOCOL_UNSUPPORTED"
